// GENERATED by tool/embed_portal.py from assets/portal/* - do not edit by hand.
// Edit the files in assets/portal/ and run: python tool/embed_portal.py
// ignore_for_file: lines_longer_than_80_chars

/// Source: assets/portal/index.html
const String portalIndexHtml = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <meta name="referrer" content="no-referrer">
  <title>VaultBox</title>
  <link rel="icon" href="data:,">
  <link rel="stylesheet" href="/portal.css">
</head>
<body>
  <noscript>
    <p class="noscript">VaultBox's web page needs JavaScript. Turn it on for this address and reload.</p>
  </noscript>
  <div id="app"></div>
  <div id="toasts" class="toasts" role="status" aria-live="polite"></div>
  <script src="/portal.js" defer></script>
</body>
</html>
''';

/// Source: assets/portal/portal.css
const String portalCss = r'''/* VaultBox web portal — Aurora Glass tokens (see lib/core/design/aurora_colors.dart).
   No external fonts or images: this page is served from a phone and must work offline. */

:root {
  color-scheme: light dark;
  --canvas: #f0eee9;
  --surface: #ffffff;
  --surface-alt: #f7f7f5;
  --ink: #1a1a1a;
  --ink-2: #666666;
  --ink-3: #8a8a8a;
  --border-strong: #1a1a1a;
  --border: #dcdcdc;
  --border-soft: #e8e8e8;
  --primary: #5c50a1;
  --on-primary: #ffffff;
  --select-bg: #eef3fb;
  --select: #2a78d6;
  --danger: #a34a4a;
  --danger-bg: #fdf6f6;
  --danger-border: #c98a8a;
  --ok: #3a7a4a;
  --warn: #8a6a2a;
  --aurora: linear-gradient(135deg, #8f83d8, #b58fd0, #d98fb0);
  --focus: #2a78d6;
  --radius: 12px;
  --font: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
}

@media (prefers-color-scheme: dark) {
  :root {
    --canvas: #15151a;
    --surface: #202027;
    --surface-alt: #1a1a20;
    --ink: #f3f1eb;
    --ink-2: #b0afb4;
    --ink-3: #8a8a8a;
    --border-strong: #f3f1eb;
    --border: #3a3a42;
    --border-soft: #2a2a32;
    --primary: #c8bfff;
    --on-primary: #322670;
    --select-bg: #1e2b40;
    --select: #6aa7f2;
    --danger: #e59a9a;
    --danger-bg: #2a1717;
    --danger-border: #a34a4a;
    --ok: #7cc493;
    --warn: #e0c177;
    --focus: #6aa7f2;
  }
}

* { box-sizing: border-box; }

html, body { margin: 0; padding: 0; }

body {
  background: var(--canvas);
  color: var(--ink);
  font-family: var(--font);
  font-size: 16px;
  line-height: 1.45;
  min-height: 100vh;
}

.noscript { padding: 24px; }

:focus-visible { outline: 3px solid var(--focus); outline-offset: 2px; }

button, input, select { font: inherit; color: inherit; }

.hidden { display: none !important; }
.sr-only {
  position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px;
  overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0;
}

/* ---------- buttons ---------- */

.btn {
  display: inline-flex; align-items: center; justify-content: center; gap: 8px;
  min-height: 44px; padding: 8px 16px;
  background: var(--surface); border: 1.5px solid var(--border-strong); border-radius: var(--radius);
  cursor: pointer; font-weight: 600; white-space: nowrap;
}
.btn:hover { background: var(--surface-alt); }
.btn:disabled { opacity: 0.5; cursor: not-allowed; }
.btn.primary { background: var(--aurora); color: #1a1a1a; border-color: var(--border-strong); }
.btn.primary:hover { filter: brightness(1.05); }
.btn.danger { color: var(--danger); border-color: var(--danger-border); }
.btn.quiet { border-color: transparent; background: transparent; }
.btn.quiet:hover { background: var(--surface-alt); }
.btn.small { min-height: 36px; padding: 4px 12px; }

.icon { width: 20px; height: 20px; flex: none; fill: none; stroke: currentColor; stroke-width: 1.8; stroke-linecap: round; stroke-linejoin: round; }

/* ---------- login ---------- */

.login-wrap { min-height: 100vh; display: grid; place-items: center; padding: 24px 16px; }

.card {
  width: 100%; max-width: 420px; background: var(--surface);
  border: 1.5px solid var(--border-strong); border-radius: 20px; padding: 28px 24px;
}

.brand { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
.brand-mark { width: 40px; height: 40px; border-radius: 12px; background: var(--aurora); border: 1.5px solid var(--border-strong); flex: none; }
.brand h1 { margin: 0; font-size: 1.5rem; letter-spacing: -0.01em; }
.lede { margin: 0 0 20px; color: var(--ink-2); }

.field { display: grid; gap: 6px; margin-bottom: 16px; }
.field label { font-weight: 600; }
.field input {
  min-height: 44px; padding: 8px 12px; background: var(--surface-alt);
  border: 1.5px solid var(--border); border-radius: 10px;
}
.field input:focus { border-color: var(--focus); }

.notice {
  display: flex; gap: 10px; align-items: flex-start; margin: 0 0 16px; padding: 10px 12px;
  border: 1.5px solid var(--border); border-radius: 10px; background: var(--surface-alt);
}
.notice.error { border-color: var(--danger-border); background: var(--danger-bg); color: var(--danger); }
.notice.warn { border-color: var(--warn); color: var(--warn); }

.insecure {
  margin: 16px 0 0; padding: 10px 12px; border: 1.5px solid var(--warn); border-radius: 10px; color: var(--warn); font-size: 0.9rem;
}

/* ---------- app shell ---------- */

.topbar {
  position: sticky; top: 0; z-index: 5; display: flex; align-items: center; gap: 12px;
  padding: 10px 16px; background: var(--surface); border-bottom: 1.5px solid var(--border-strong);
}
.topbar .brand { margin: 0; }
.topbar .brand h1 { font-size: 1.15rem; }
.topbar .brand-mark { width: 30px; height: 30px; border-radius: 9px; }
.spacer { flex: 1; }
.who { color: var(--ink-2); font-size: 0.9rem; }

.page { max-width: 1100px; margin: 0 auto; padding: 16px; }

.roots { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 12px; }
.chip {
  display: inline-flex; align-items: center; gap: 8px; min-height: 40px; padding: 6px 14px;
  background: var(--surface); border: 1.5px solid var(--border); border-radius: 999px; cursor: pointer; font-weight: 600;
}
.chip[aria-current="true"] { border-color: var(--border-strong); background: var(--select-bg); }
.chip small { color: var(--ink-3); font-weight: 400; }

.crumbs { display: flex; align-items: center; flex-wrap: wrap; gap: 2px; margin: 4px 0 12px; }
.crumbs button {
  min-height: 36px; padding: 4px 10px; background: transparent; border: 0; border-radius: 8px; cursor: pointer;
  font-weight: 600; color: var(--ink);
}
.crumbs button:hover { background: var(--surface); }
.crumbs button[aria-current="page"] { cursor: default; color: var(--ink-2); }
.crumbs .sep { color: var(--ink-3); }

.toolbar { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; align-items: center; }
.toolbar .count { color: var(--ink-2); font-weight: 600; margin-right: 4px; }

.panel {
  background: var(--surface); border: 1.5px solid var(--border-strong); border-radius: var(--radius); overflow: hidden;
}
.panel.dragging { outline: 3px dashed var(--select); outline-offset: 3px; }

table.files { width: 100%; border-collapse: collapse; }
table.files th {
  text-align: left; padding: 10px 12px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em;
  color: var(--ink-2); border-bottom: 1.5px solid var(--border); background: var(--surface-alt);
}
table.files td { padding: 6px 12px; border-bottom: 1px solid var(--border-soft); vertical-align: middle; }
table.files tr:last-child td { border-bottom: 0; }
table.files tr.selected td { background: var(--select-bg); }
table.files .check { width: 44px; padding-right: 0; }
table.files .num { text-align: right; white-space: nowrap; color: var(--ink-2); font-family: var(--mono); font-size: 0.85rem; }
table.files .when { white-space: nowrap; color: var(--ink-2); font-size: 0.9rem; }
table.files input[type="checkbox"] { width: 20px; height: 20px; accent-color: var(--select); }

.name-btn {
  display: inline-flex; align-items: center; gap: 10px; min-height: 40px; padding: 4px 6px; max-width: 100%;
  background: transparent; border: 0; border-radius: 8px; cursor: pointer; text-align: left; font-weight: 600;
}
.name-btn:hover { background: var(--surface-alt); }
.name-btn .label { overflow-wrap: anywhere; }
.name-btn.file { font-weight: 500; }

.empty { padding: 40px 16px; text-align: center; color: var(--ink-2); }
.empty strong { display: block; color: var(--ink); font-size: 1.1rem; margin-bottom: 4px; }

.more { display: flex; justify-content: center; padding: 12px; border-top: 1px solid var(--border-soft); }

/* ---------- uploads + toasts ---------- */

.uploads {
  position: fixed; right: 16px; bottom: 16px; z-index: 8; width: min(360px, calc(100vw - 32px));
  background: var(--surface); border: 1.5px solid var(--border-strong); border-radius: var(--radius); overflow: hidden;
}
.uploads header { display: flex; align-items: center; gap: 8px; padding: 8px 12px; border-bottom: 1.5px solid var(--border); font-weight: 600; }
.uploads ul { list-style: none; margin: 0; padding: 0; max-height: 220px; overflow: auto; }
.uploads li { padding: 8px 12px; border-bottom: 1px solid var(--border-soft); }
.uploads li:last-child { border-bottom: 0; }
.uploads .row { display: flex; justify-content: space-between; gap: 8px; font-size: 0.9rem; }
.uploads .row .n { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.uploads .row .s { color: var(--ink-2); white-space: nowrap; }
.uploads .row .s.bad { color: var(--danger); }
.uploads .row .s.good { color: var(--ok); }
.bar { height: 6px; margin-top: 6px; background: var(--border-soft); border-radius: 999px; overflow: hidden; }
.bar > span { display: block; height: 100%; width: 0; background: var(--aurora); }

.toasts { position: fixed; left: 50%; bottom: 16px; transform: translateX(-50%); z-index: 20; display: grid; gap: 8px; width: min(440px, calc(100vw - 32px)); pointer-events: none; }
.toast {
  pointer-events: auto; padding: 10px 14px; background: var(--ink); color: var(--canvas);
  border-radius: 10px; font-weight: 500;
}
.toast.error { background: var(--danger); color: #fff; }

/* ---------- dialogs ---------- */

dialog {
  width: min(520px, calc(100vw - 24px)); max-height: calc(100vh - 24px); padding: 0;
  background: var(--surface); color: var(--ink); border: 1.5px solid var(--border-strong); border-radius: 16px;
}
dialog::backdrop { background: rgba(20, 20, 26, 0.55); }
dialog form { display: flex; flex-direction: column; max-height: calc(100vh - 24px); margin: 0; }
dialog .d-head { display: flex; align-items: center; gap: 8px; padding: 14px 16px; border-bottom: 1.5px solid var(--border); }
dialog .d-head h2 { margin: 0; font-size: 1.1rem; flex: 1; overflow-wrap: anywhere; }
dialog .d-body { padding: 16px; overflow: auto; }
dialog .d-foot { display: flex; justify-content: flex-end; gap: 8px; padding: 12px 16px; border-top: 1.5px solid var(--border); flex-wrap: wrap; }
dialog.wide { width: min(900px, calc(100vw - 24px)); }
dialog .d-body p { margin: 0 0 12px; }

.picker-list { list-style: none; margin: 8px 0 0; padding: 0; border: 1.5px solid var(--border); border-radius: 10px; max-height: 280px; overflow: auto; }
.picker-list li { border-bottom: 1px solid var(--border-soft); }
.picker-list li:last-child { border-bottom: 0; }
.picker-list button { width: 100%; }
.picker-path { font-family: var(--mono); font-size: 0.85rem; color: var(--ink-2); overflow-wrap: anywhere; }

.preview img, .preview video { display: block; max-width: 100%; max-height: 70vh; margin: 0 auto; background: var(--surface-alt); border-radius: 8px; }
.preview audio { width: 100%; }
.preview pre { margin: 0; max-height: 60vh; overflow: auto; padding: 12px; background: var(--surface-alt); border-radius: 8px; white-space: pre-wrap; overflow-wrap: anywhere; font-family: var(--mono); font-size: 0.85rem; }

.radio-row { display: flex; gap: 16px; flex-wrap: wrap; margin-top: 8px; }
.radio-row label { display: inline-flex; align-items: center; gap: 6px; min-height: 36px; }

/* ---------- small screens ---------- */

@media (max-width: 640px) {
  .page { padding: 12px; }
  table.files .when, table.files th.when { display: none; }
  .who { display: none; }
  .btn .txt { display: none; }
  .btn.keep-text .txt { display: inline; }
  .toolbar .btn { padding: 8px 12px; }
}

@media (prefers-reduced-motion: reduce) {
  * { animation: none !important; transition: none !important; }
}
''';

/// Source: assets/portal/portal.js
const String portalJs = r'''/* VaultBox web portal.
 *
 * One dependency-free page. It talks to the same versioned API as any other
 * client (/api/v1/...) using a bearer token kept in sessionStorage — never a
 * cookie, so a page on another site cannot make this browser act for you.
 *
 * Everything shown to the person is inserted with textContent / text nodes.
 * Nothing here builds HTML from a file name or a server message, and the page's
 * Content-Security-Policy forbids inline script anyway.
 */
"use strict";

(function () {
  var TOKEN_KEY = "vb.token";
  var RESUME_KEY = "vb.resume";
  var PAGE_SIZE = 200;
  var MAX_TEXT_PREVIEW = 512 * 1024;

  var appEl = document.getElementById("app");
  var toastsEl = document.getElementById("toasts");

  // ---------------------------------------------------------------- helpers

  var store = {
    get: function (key) {
      try { return window.sessionStorage.getItem(key); } catch (_) { return null; }
    },
    set: function (key, value) {
      try {
        if (value === null || value === undefined) window.sessionStorage.removeItem(key);
        else window.sessionStorage.setItem(key, value);
      } catch (_) { /* storage unavailable: the page still works, it just forgets on reload */ }
    },
  };

  function append(node, children) {
    for (var i = 0; i < children.length; i++) {
      var child = children[i];
      if (child === null || child === undefined || child === false) continue;
      if (Array.isArray(child)) append(node, child);
      else node.append(child instanceof Node ? child : document.createTextNode(String(child)));
    }
  }

  /** h("button", {class: "btn", onclick: fn}, "Label", iconNode) */
  function h(tag, attrs) {
    var node = document.createElement(tag);
    var keys = attrs ? Object.keys(attrs) : [];
    for (var i = 0; i < keys.length; i++) {
      var key = keys[i];
      var value = attrs[key];
      if (value === null || value === undefined || value === false) continue;
      if (key === "class") node.className = value;
      else if (key === "text") node.textContent = value;
      else if (key.indexOf("on") === 0) node.addEventListener(key.slice(2), value);
      else if (key === "value" || key === "checked" || key === "disabled") node[key] = value;
      else node.setAttribute(key, value === true ? "" : String(value));
    }
    append(node, Array.prototype.slice.call(arguments, 2));
    return node;
  }

  var SVG_NS = "http://www.w3.org/2000/svg";
  var ICONS = {
    folder: ["M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"],
    file: ["M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z", "M14 3v5h5"],
    image: ["M4 5h16v14H4z", "M4 17l5-5 4 4 3-3 4 4", "M9 9.5h.01"],
    video: ["M4 6h12v12H4z", "M16 10l5-3v10l-5-3"],
    audio: ["M9 18V6l10-2v12", "M9 18a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0", "M19 16a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"],
    upload: ["M12 16V4", "M7 9l5-5 5 5", "M4 20h16"],
    download: ["M12 4v12", "M7 11l5 5 5-5", "M4 20h16"],
    newfolder: ["M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", "M12 10v6", "M9 13h6"],
    trash: ["M4 7h16", "M10 11v6", "M14 11v6", "M6 7l1 13h10l1-13", "M9 7V4h6v3"],
    edit: ["M4 20l4-1 11-11-3-3L5 16z", "M14 6l3 3"],
    move: ["M5 12h14", "M13 6l6 6-6 6"],
    copy: ["M9 9h10v10H9z", "M5 15V5h10"],
    refresh: ["M20 11a8 8 0 1 0-2.3 5.7", "M20 5v6h-6"],
    logout: ["M9 4H5v16h4", "M16 8l4 4-4 4", "M20 12H9"],
    close: ["M6 6l12 12", "M18 6L6 18"],
    up: ["M12 19V5", "M6 11l6-6 6 6"],
    view: ["M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z", "M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"],
  };

  function icon(name) {
    var svg = document.createElementNS(SVG_NS, "svg");
    svg.setAttribute("viewBox", "0 0 24 24");
    svg.setAttribute("class", "icon");
    svg.setAttribute("aria-hidden", "true");
    var paths = ICONS[name] || ICONS.file;
    for (var i = 0; i < paths.length; i++) {
      var path = document.createElementNS(SVG_NS, "path");
      path.setAttribute("d", paths[i]);
      svg.appendChild(path);
    }
    return svg;
  }

  function button(label, iconName, options) {
    var opts = options || {};
    var classes = "btn" + (opts.kind ? " " + opts.kind : "") + (opts.small ? " small" : "") + (opts.keepText ? " keep-text" : "");
    return h(
      "button",
      { type: opts.type || "button", class: classes, onclick: opts.onclick, disabled: opts.disabled, "aria-label": opts.iconOnly ? label : null, title: label },
      iconName ? icon(iconName) : null,
      opts.iconOnly ? null : h("span", { class: "txt", text: label })
    );
  }

  function encode(text) {
    return encodeURIComponent(text);
  }

  function formatBytes(bytes) {
    if (bytes === null || bytes === undefined) return "";
    if (bytes < 1024) return bytes + " B";
    var units = ["KB", "MB", "GB", "TB"];
    var value = bytes / 1024;
    var unit = 0;
    while (value >= 1024 && unit < units.length - 1) {
      value /= 1024;
      unit++;
    }
    return (value >= 10 ? value.toFixed(0) : value.toFixed(1)) + " " + units[unit];
  }

  function formatWhen(iso) {
    if (!iso) return "";
    var date = new Date(iso);
    if (isNaN(date.getTime())) return "";
    try {
      return date.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
    } catch (_) {
      return date.toISOString();
    }
  }

  var EXTENSIONS = {
    image: ["png", "jpg", "jpeg", "gif", "webp", "bmp"],
    video: ["mp4", "m4v", "webm", "mov", "3gp"],
    audio: ["mp3", "m4a", "aac", "wav", "ogg", "flac"],
    text: ["txt", "md", "log", "csv"],
  };

  function kindOf(name) {
    var dot = name.lastIndexOf(".");
    if (dot <= 0) return "file";
    var ext = name.slice(dot + 1).toLowerCase();
    var kinds = Object.keys(EXTENSIONS);
    for (var i = 0; i < kinds.length; i++) {
      if (EXTENSIONS[kinds[i]].indexOf(ext) !== -1) return kinds[i];
    }
    return "file";
  }

  function iconFor(entry) {
    if (entry.type === "directory") return "folder";
    var kind = kindOf(entry.name);
    return kind === "text" ? "file" : kind === "file" ? "file" : kind;
  }

  function joinPath(directory, name) {
    return directory === "/" ? "/" + name : directory + "/" + name;
  }

  function parentPath(path) {
    var cut = path.lastIndexOf("/");
    return cut <= 0 ? "/" : path.slice(0, cut);
  }

  function pathSegments(path) {
    return path.split("/").filter(function (part) { return part.length > 0; });
  }

  var MESSAGES = {
    invalid_credentials: "That username and password don't match.",
    too_many_attempts: "Too many attempts.",
    busy: "The phone is busy right now. Try again in a moment.",
    unauthorized: "Your session ended. Sign in again to continue.",
    forbidden: "You don't have permission to do that.",
    read_only_storage: "This storage is read-only.",
    not_found: "That item no longer exists.",
    root_not_found: "That storage location isn't available.",
    storage_unavailable: "That storage isn't reachable right now.",
    storage_permission_revoked: "VaultBox lost access to this storage. Reconnect it on the phone.",
    already_exists: "Something with that name already exists.",
    parent_not_found: "That folder no longer exists.",
    destination_not_found: "The destination folder no longer exists.",
    invalid_name: "That name can't be used.",
    invalid_path: "That location isn't allowed.",
    is_a_directory: "A folder with that name already exists.",
    not_a_file: "That is a folder, not a file.",
    insufficient_storage: "There isn't enough free space on the phone.",
    upload_interrupted: "The upload was interrupted.",
    payload_too_large: "That request was too large.",
    network: "Can't reach the phone. Check that it is on and on the same network.",
  };

  function describeError(error) {
    if (error && error.code === "too_many_attempts" && error.retryAfter) {
      return "Too many attempts. Try again in " + error.retryAfter + " seconds.";
    }
    if (error && MESSAGES[error.code]) return MESSAGES[error.code];
    return "Something went wrong. Please try again.";
  }

  function toast(message, isError) {
    var node = h("div", { class: "toast" + (isError ? " error" : ""), text: message });
    toastsEl.appendChild(node);
    window.setTimeout(function () { node.remove(); }, isError ? 8000 : 5000);
  }

  // ------------------------------------------------------------------ state

  var state = {
    token: store.get(TOKEN_KEY),
    user: null,
    roots: [],
    rootId: null,
    path: "/",
    entries: [],
    next: null,
    loading: false,
    error: null,
    selected: new Set(),
  };
  var loadCounter = 0;
  var shell = null;
  var collator = new Intl.Collator(undefined, { numeric: true, sensitivity: "base" });

  function currentRoot() {
    for (var i = 0; i < state.roots.length; i++) {
      if (state.roots[i].id === state.rootId) return state.roots[i];
    }
    return null;
  }

  function canWrite() {
    var root = currentRoot();
    return !!root && root.writable === true && root.available !== false;
  }

  // -------------------------------------------------------------------- API

  function ApiError(status, code, retryAfter) {
    this.name = "ApiError";
    this.status = status;
    this.code = code;
    this.retryAfter = retryAfter;
  }
  ApiError.prototype = Object.create(Error.prototype);

  function request(method, path, options) {
    var opts = options || {};
    var url = new URL(path, window.location.origin);
    var query = opts.query || {};
    Object.keys(query).forEach(function (key) {
      if (query[key] !== undefined && query[key] !== null) url.searchParams.set(key, String(query[key]));
    });

    var init = { method: method, headers: {}, cache: "no-store", credentials: "omit", referrerPolicy: "no-referrer" };
    var authed = opts.auth !== false;
    if (authed && state.token) init.headers.Authorization = "Bearer " + state.token;
    if (opts.json !== undefined) {
      init.headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(opts.json);
    }

    return fetch(url.toString(), init).then(
      function (response) {
        if (response.status === 401 && authed && state.token) {
          endSession("Your session ended. Sign in again to continue.");
          throw new ApiError(401, "unauthorized", null);
        }
        if (!response.ok) {
          return response.json().then(
            function (data) { return data; },
            function () { return null; }
          ).then(function (data) {
            var code = data && typeof data.error === "string" ? data.error : "error";
            throw new ApiError(response.status, code, response.headers.get("Retry-After"));
          });
        }
        if (response.status === 204) return null;
        return response.json();
      },
      function () {
        throw new ApiError(0, "network", null);
      }
    );
  }

  function rootUrl(action) {
    return "/api/v1/roots/" + encode(state.rootId) + "/" + action;
  }

  // ------------------------------------------------------------ session flow

  function endSession(message) {
    if (!state.token && !shell) return;
    var resume = window.location.hash;
    store.set(RESUME_KEY, resume && resume.length > 1 ? resume : null);
    state.token = null;
    state.user = null;
    store.set(TOKEN_KEY, null);
    shell = null;
    renderLogin(message || null);
  }

  function signOut() {
    request("POST", "/api/v1/auth/logout").then(
      function () {},
      function () {}
    ).then(function () {
      state.token = null;
      state.user = null;
      store.set(TOKEN_KEY, null);
      store.set(RESUME_KEY, null);
      shell = null;
      window.location.hash = "";
      renderLogin(null);
    });
  }

  // ------------------------------------------------------------------ login

  function renderLogin(message) {
    var insecure = window.location.protocol === "http:" &&
      ["localhost", "127.0.0.1", "[::1]"].indexOf(window.location.hostname) === -1;

    var errorBox = h("p", { class: "notice error hidden", role: "alert" });
    var infoBox = message ? h("p", { class: "notice", role: "status", text: message }) : null;
    var username = h("input", { id: "username", name: "username", type: "text", autocomplete: "username", autocapitalize: "none", spellcheck: "false", required: true });
    var password = h("input", { id: "password", name: "password", type: "password", autocomplete: "current-password", required: true });
    var submit = button("Sign in", null, { type: "submit", kind: "primary", keepText: true });

    function fail(text) {
      errorBox.textContent = text;
      errorBox.classList.remove("hidden");
    }

    var form = h(
      "form",
      {
        novalidate: true,
        onsubmit: function (event) {
          event.preventDefault();
          if (!username.value.trim() || !password.value) {
            fail("Enter your username and password.");
            return;
          }
          errorBox.classList.add("hidden");
          submit.disabled = true;
          request("POST", "/api/v1/auth/login", { json: { username: username.value, password: password.value }, auth: false }).then(
            function (data) {
              state.token = data.token;
              state.user = data.user;
              store.set(TOKEN_KEY, data.token);
              password.value = "";
              return enterApp();
            },
            function (error) {
              submit.disabled = false;
              password.value = "";
              password.focus();
              fail(describeError(error));
            }
          );
        },
      },
      infoBox,
      errorBox,
      h("div", { class: "field" }, h("label", { for: "username", text: "Username" }), username),
      h("div", { class: "field" }, h("label", { for: "password", text: "Password" }), password),
      submit
    );

    appEl.replaceChildren(
      h(
        "div",
        { class: "login-wrap" },
        h(
          "main",
          { class: "card" },
          h("div", { class: "brand" }, h("span", { class: "brand-mark", "aria-hidden": "true" }), h("h1", { text: "VaultBox" })),
          h("p", { class: "lede", text: "Sign in to reach the files on this phone." }),
          form,
          insecure
            ? h("p", { class: "insecure", text: "This connection isn't encrypted, so anyone on this network could read your password and files. Use the https:// address if you can." })
            : null
        )
      )
    );
    username.focus();
  }

  // -------------------------------------------------------------- app entry

  function enterApp() {
    return Promise.all([
      state.user ? Promise.resolve(state.user) : request("GET", "/api/v1/me"),
      request("GET", "/api/v1/roots"),
    ]).then(
      function (results) {
        state.user = results[0];
        state.roots = results[1].roots;
        buildShell();
        var resume = store.get(RESUME_KEY);
        if (resume) {
          store.set(RESUME_KEY, null);
          if (window.location.hash !== resume) window.location.hash = resume;
        }
        route();
      },
      function (error) {
        if (error && error.code === "unauthorized") return;
        state.token = null;
        store.set(TOKEN_KEY, null);
        renderLogin(describeError(error));
      }
    );
  }

  function buildHash(rootId, path) {
    return "#/" + encode(rootId) + (path === "/" ? "/" : "/" + pathSegments(path).map(encode).join("/"));
  }

  function parseHash() {
    var hash = window.location.hash;
    if (hash.indexOf("#/") !== 0) return null;
    var rest = hash.slice(2);
    var cut = rest.indexOf("/");
    var rawRoot = cut === -1 ? rest : rest.slice(0, cut);
    var rawPath = cut === -1 ? "" : rest.slice(cut + 1);
    try {
      var segments = rawPath.split("/").filter(Boolean).map(decodeURIComponent);
      return { rootId: decodeURIComponent(rawRoot), path: "/" + segments.join("/") };
    } catch (_) {
      return null;
    }
  }

  function goTo(rootId, path) {
    var wanted = buildHash(rootId, path);
    if (window.location.hash === wanted) route();
    else window.location.hash = wanted;
  }

  function route() {
    if (!state.token || !shell) return;
    var target = parseHash();
    var known = target && state.roots.some(function (root) { return root.id === target.rootId; });
    if (!known) {
      var preferred = state.roots.filter(function (root) { return root.isDefault; })[0] || state.roots[0];
      if (!preferred) {
        state.rootId = null;
        renderRoots();
        renderCrumbs();
        renderToolbar();
        renderFiles();
        return;
      }
      target = { rootId: preferred.id, path: "/" };
      window.history.replaceState(null, "", buildHash(target.rootId, target.path));
    }
    state.rootId = target.rootId;
    state.path = target.path;
    renderRoots();
    renderCrumbs();
    loadDirectory(true);
  }

  window.addEventListener("hashchange", route);

  // ------------------------------------------------------------------ shell

  function buildShell() {
    shell = {
      roots: h("nav", { class: "roots", "aria-label": "Storage locations" }),
      crumbs: h("nav", { class: "crumbs", "aria-label": "Folder path" }),
      toolbar: h("div", { class: "toolbar", role: "toolbar", "aria-label": "File actions" }),
      panel: h("section", { class: "panel", "aria-label": "Files" }),
      uploads: h("aside", { class: "uploads hidden", "aria-label": "Uploads" }),
      fileInput: h("input", {
        type: "file",
        multiple: true,
        class: "hidden",
        "aria-hidden": "true",
        tabindex: "-1",
        onchange: function (event) {
          var files = Array.prototype.slice.call(event.target.files);
          event.target.value = "";
          queueUploads(files);
        },
      }),
    };

    var panel = shell.panel;
    panel.addEventListener("dragover", function (event) {
      if (!canWrite() || !hasFiles(event)) return;
      event.preventDefault();
      panel.classList.add("dragging");
    });
    panel.addEventListener("dragleave", function () { panel.classList.remove("dragging"); });
    panel.addEventListener("drop", function (event) {
      panel.classList.remove("dragging");
      if (!canWrite() || !hasFiles(event)) return;
      event.preventDefault();
      collectDropped(event.dataTransfer);
    });

    appEl.replaceChildren(
      h(
        "header",
        { class: "topbar" },
        h("div", { class: "brand" }, h("span", { class: "brand-mark", "aria-hidden": "true" }), h("h1", { text: "VaultBox" })),
        h("span", { class: "spacer" }),
        h("span", { class: "who", text: state.user ? state.user.username : "" }),
        button("Sign out", "logout", { onclick: signOut, small: true, kind: "quiet" })
      ),
      h("main", { class: "page" }, shell.roots, shell.crumbs, shell.toolbar, shell.panel),
      shell.uploads,
      shell.fileInput
    );
    window.addEventListener("beforeunload", warnIfUploading);
  }

  function hasFiles(event) {
    var types = event.dataTransfer && event.dataTransfer.types;
    return !!types && Array.prototype.indexOf.call(types, "Files") !== -1;
  }

  function warnIfUploading(event) {
    if (uploads.items.some(function (item) { return item.status === "uploading" || item.status === "waiting"; })) {
      event.preventDefault();
      event.returnValue = "";
    }
  }

  function renderRoots() {
    if (state.roots.length < 2) {
      shell.roots.replaceChildren();
      return;
    }
    shell.roots.replaceChildren.apply(
      shell.roots,
      state.roots.map(function (root) {
        return h(
          "button",
          {
            type: "button",
            class: "chip",
            "aria-current": root.id === state.rootId ? "true" : "false",
            onclick: function () { goTo(root.id, "/"); },
          },
          icon("folder"),
          root.name,
          root.available === false ? h("small", { text: "offline" }) : null,
          root.writable === false ? h("small", { text: "read-only" }) : null
        );
      })
    );
  }

  function renderCrumbs() {
    var root = currentRoot();
    if (!root) {
      shell.crumbs.replaceChildren();
      return;
    }
    var parts = pathSegments(state.path);
    var nodes = [];
    nodes.push(crumb(root.name, "/", parts.length === 0));
    var walked = "";
    parts.forEach(function (part, index) {
      walked += "/" + part;
      nodes.push(h("span", { class: "sep", "aria-hidden": "true", text: "/" }));
      nodes.push(crumb(part, walked, index === parts.length - 1));
    });
    shell.crumbs.replaceChildren.apply(shell.crumbs, nodes);
  }

  function crumb(label, path, isCurrent) {
    return h("button", {
      type: "button",
      text: label,
      "aria-current": isCurrent ? "page" : null,
      onclick: function () { if (!isCurrent) goTo(state.rootId, path); },
    });
  }

  // --------------------------------------------------------------- toolbar

  function selectedEntries() {
    return state.entries.filter(function (entry) { return state.selected.has(entry.name); });
  }

  function renderToolbar() {
    var root = currentRoot();
    if (!root) {
      shell.toolbar.replaceChildren();
      return;
    }
    var chosen = selectedEntries();
    var writable = canWrite();
    var nodes = [];

    if (chosen.length === 0) {
      if (writable) {
        nodes.push(button("Upload", "upload", { kind: "primary", keepText: true, onclick: function () { shell.fileInput.click(); } }));
        nodes.push(button("New folder", "newfolder", { onclick: newFolder }));
      }
      nodes.push(button("Refresh", "refresh", { onclick: function () { loadDirectory(true); } }));
    } else {
      nodes.push(h("span", { class: "count", text: chosen.length + " selected" }));
      var single = chosen.length === 1 ? chosen[0] : null;
      if (single && single.type === "file") {
        var kind = kindOf(single.name);
        if (kind !== "file") nodes.push(button("Preview", "view", { onclick: function () { previewFile(single); } }));
        nodes.push(button("Download", "download", { onclick: function () { downloadFile(single); } }));
      }
      if (writable) {
        if (single) nodes.push(button("Rename", "edit", { onclick: function () { renameEntry(single); } }));
        nodes.push(button("Move", "move", { onclick: function () { moveOrCopy(chosen, true); } }));
        nodes.push(button("Copy", "copy", { onclick: function () { moveOrCopy(chosen, false); } }));
        nodes.push(button("Delete", "trash", { kind: "danger", onclick: function () { deleteEntries(chosen); } }));
      }
      nodes.push(button("Clear", "close", { kind: "quiet", onclick: function () { state.selected.clear(); renderFiles(); renderToolbar(); } }));
    }
    shell.toolbar.replaceChildren.apply(shell.toolbar, nodes);
  }

  // ------------------------------------------------------------- file list

  function sortEntries() {
    state.entries.sort(function (a, b) {
      if (a.type !== b.type) return a.type === "directory" ? -1 : 1;
      return collator.compare(a.name, b.name);
    });
  }

  function loadDirectory(reset) {
    var mine = ++loadCounter;
    if (reset) {
      state.entries = [];
      state.next = null;
      state.selected.clear();
    }
    state.loading = true;
    state.error = null;
    renderFiles();
    renderToolbar();

    var query = { path: state.path, limit: PAGE_SIZE };
    if (!reset && state.next) query.cursor = state.next;

    return request("GET", rootUrl("entries"), { query: query }).then(
      function (data) {
        if (mine !== loadCounter) return;
        state.entries = state.entries.concat(data.entries);
        sortEntries();
        state.next = data.nextCursor;
        state.loading = false;
        renderFiles();
        renderToolbar();
      },
      function (error) {
        if (mine !== loadCounter) return;
        state.loading = false;
        state.error = describeError(error);
        renderFiles();
        renderToolbar();
      }
    );
  }

  function renderFiles() {
    var panel = shell.panel;
    if (!state.rootId) {
      panel.replaceChildren(emptyState("No storage is shared yet", "Add a storage location in the VaultBox app on the phone."));
      return;
    }
    if (state.error) {
      panel.replaceChildren(
        h("div", { class: "empty" }, h("strong", { text: "Couldn't open this folder" }), h("p", { text: state.error }), button("Try again", "refresh", { onclick: function () { loadDirectory(true); } }))
      );
      return;
    }
    if (state.loading && state.entries.length === 0) {
      panel.replaceChildren(h("div", { class: "empty", role: "status", text: "Loading…" }));
      return;
    }
    if (state.entries.length === 0) {
      panel.replaceChildren(
        emptyState("This folder is empty", canWrite() ? "Drop files here or use Upload." : "Nothing here yet.")
      );
      return;
    }

    var allSelected = state.entries.length > 0 && state.entries.every(function (entry) { return state.selected.has(entry.name); });
    var headCheck = h("input", {
      type: "checkbox",
      checked: allSelected,
      "aria-label": "Select all",
      onchange: function (event) {
        if (event.target.checked) state.entries.forEach(function (entry) { state.selected.add(entry.name); });
        else state.selected.clear();
        renderFiles();
        renderToolbar();
      },
    });

    var body = h("tbody");
    state.entries.forEach(function (entry) {
      body.appendChild(renderRow(entry));
    });

    var nodes = [
      h(
        "table",
        { class: "files" },
        h("thead", null, h("tr", null, h("th", { class: "check" }, headCheck), h("th", { text: "Name" }), h("th", { class: "num", text: "Size" }), h("th", { class: "when", text: "Modified" }))),
        body
      ),
    ];
    if (state.next) {
      nodes.push(
        h("div", { class: "more" }, button(state.loading ? "Loading…" : "Load more", null, { keepText: true, disabled: state.loading, onclick: function () { loadDirectory(false); } }))
      );
    }
    panel.replaceChildren.apply(panel, nodes);
  }

  function emptyState(title, text) {
    return h("div", { class: "empty" }, h("strong", { text: title }), h("span", { text: text }));
  }

  function renderRow(entry) {
    var isDir = entry.type === "directory";
    var checked = state.selected.has(entry.name);
    var row = h("tr", { class: checked ? "selected" : null });

    var check = h("input", {
      type: "checkbox",
      checked: checked,
      "aria-label": "Select " + entry.name,
      onchange: function (event) {
        if (event.target.checked) state.selected.add(entry.name);
        else state.selected.delete(entry.name);
        row.classList.toggle("selected", event.target.checked);
        renderToolbar();
      },
    });

    var open = h(
      "button",
      {
        type: "button",
        class: "name-btn" + (isDir ? "" : " file"),
        onclick: function () {
          if (isDir) goTo(state.rootId, joinPath(state.path, entry.name));
          else openFile(entry);
        },
      },
      icon(iconFor(entry)),
      h("span", { class: "label", text: entry.name })
    );

    row.append(
      h("td", { class: "check" }, check),
      h("td", null, open),
      h("td", { class: "num", text: isDir ? "" : formatBytes(entry.size) }),
      h("td", { class: "when", text: formatWhen(entry.modified) })
    );
    return row;
  }

  function openFile(entry) {
    if (kindOf(entry.name) !== "file") previewFile(entry);
    else downloadFile(entry);
  }

  // ---------------------------------------------------------------- dialogs

  /**
   * A modal. [actions] are {label, value, kind, submit}. Resolves with the
   * chosen action's value, or null if dismissed. The one with `submit: true`
   * runs on Enter; its optional `check()` can veto closing.
   */
  function showDialog(title, content, actions, options) {
    var opts = options || {};
    return new Promise(function (resolve) {
      var dialog = h("dialog", { class: opts.wide ? "wide" : null, "aria-label": title });
      var done = false;

      function close(value) {
        if (done) return;
        done = true;
        if (dialog.open) dialog.close();
        dialog.remove();
        resolve(value);
      }

      var foot = h("div", { class: "d-foot" });
      actions.forEach(function (action) {
        foot.appendChild(
          h("button", {
            type: action.submit ? "submit" : "button",
            class: "btn" + (action.kind ? " " + action.kind : ""),
            text: action.label,
            onclick: action.submit ? null : function () { close(action.value); },
          })
        );
      });

      var submitAction = actions.filter(function (action) { return action.submit; })[0];
      var form = h(
        "form",
        {
          method: "dialog",
          onsubmit: function (event) {
            event.preventDefault();
            if (!submitAction) return;
            if (submitAction.check && submitAction.check() === false) return;
            close(submitAction.value);
          },
        },
        h("div", { class: "d-head" }, h("h2", { text: title }), h("button", { type: "button", class: "btn quiet small", "aria-label": "Close", onclick: function () { close(null); } }, icon("close"))),
        h("div", { class: "d-body" }, content),
        foot
      );
      dialog.appendChild(form);
      dialog.addEventListener("cancel", function (event) {
        event.preventDefault();
        close(null);
      });
      document.body.appendChild(dialog);
      dialog.showModal();
      var first = dialog.querySelector("input[type=text], input:not([type=hidden])");
      if (first && typeof first.select === "function") first.select();
    });
  }

  function promptText(options) {
    var input = h("input", { type: "text", id: "prompt-input", value: options.value || "", autocomplete: "off", autocapitalize: "none", spellcheck: "false" });
    var problem = h("p", { class: "notice error hidden", role: "alert" });
    var content = h("div", null, problem, h("div", { class: "field" }, h("label", { for: "prompt-input", text: options.label }), input));
    return showDialog(
      options.title,
      content,
      [
        { label: "Cancel", value: null },
        {
          label: options.confirmLabel,
          value: "ok",
          kind: "primary",
          submit: true,
          check: function () {
            var text = input.value.trim();
            if (!text) {
              problem.textContent = "Enter a name.";
              problem.classList.remove("hidden");
              return false;
            }
            if (text.indexOf("/") !== -1 || text.indexOf("\\") !== -1) {
              problem.textContent = "A name can't contain / or \\.";
              problem.classList.remove("hidden");
              return false;
            }
            return true;
          },
        },
      ]
    ).then(function (result) {
      return result === "ok" ? input.value.trim() : null;
    });
  }

  function confirmDialog(options) {
    return showDialog(
      options.title,
      h("p", { text: options.message }),
      [
        { label: "Cancel", value: false },
        { label: options.confirmLabel, value: true, kind: options.danger ? "danger" : "primary", submit: true },
      ]
    ).then(function (result) { return result === true; });
  }

  // ----------------------------------------------------------- file actions

  function withTicket(entry) {
    var path = joinPath(state.path, entry.name);
    return request("POST", rootUrl("ticket"), { json: { path: path } }).then(function (data) {
      if (!data || typeof data.url !== "string" || data.url.indexOf("/d/") !== 0) throw new ApiError(500, "error", null);
      return data.url;
    });
  }

  function downloadFile(entry) {
    withTicket(entry).then(
      function (url) {
        var link = h("a", { href: url, download: entry.name, rel: "noopener" });
        document.body.appendChild(link);
        link.click();
        link.remove();
      },
      function (error) { toast(describeError(error), true); }
    );
  }

  function previewFile(entry) {
    var kind = kindOf(entry.name);
    if (kind === "file") {
      downloadFile(entry);
      return;
    }
    if (kind === "text" && typeof entry.size === "number" && entry.size > MAX_TEXT_PREVIEW) {
      toast("That file is too large to preview. Downloading instead.");
      downloadFile(entry);
      return;
    }
    withTicket(entry).then(
      function (url) {
        var media;
        if (kind === "image") media = h("img", { src: url + "?inline=1", alt: entry.name });
        else if (kind === "video") media = h("video", { src: url + "?inline=1", controls: true, preload: "metadata" });
        else if (kind === "audio") media = h("audio", { src: url + "?inline=1", controls: true, preload: "metadata" });
        else {
          media = h("pre", { text: "Loading…" });
          fetch(url + "?inline=1", { credentials: "omit", cache: "no-store", referrerPolicy: "no-referrer" })
            .then(function (response) { return response.text(); })
            .then(function (text) { media.textContent = text; }, function () { media.textContent = "Couldn't load this file."; });
        }
        showDialog(
          entry.name,
          h("div", { class: "preview" }, media),
          [{ label: "Close", value: null }, { label: "Download", value: "download", kind: "primary", submit: true }],
          { wide: true }
        ).then(function (result) {
          if (media.pause) media.pause();
          if (result === "download") downloadFile(entry);
        });
      },
      function (error) { toast(describeError(error), true); }
    );
  }

  function newFolder() {
    promptText({ title: "New folder", label: "Folder name", confirmLabel: "Create" }).then(function (name) {
      if (!name) return;
      request("POST", rootUrl("mkdir"), { json: { path: joinPath(state.path, name) } }).then(
        function () {
          toast("Created “" + name + "”.");
          loadDirectory(true);
        },
        function (error) { toast(describeError(error), true); }
      );
    });
  }

  function renameEntry(entry) {
    promptText({ title: "Rename", label: "New name", value: entry.name, confirmLabel: "Rename" }).then(function (name) {
      if (!name || name === entry.name) return;
      request("POST", rootUrl("rename"), { json: { path: joinPath(state.path, entry.name), newName: name } }).then(
        function () {
          loadDirectory(true);
        },
        function (error) { toast(describeError(error), true); }
      );
    });
  }

  function deleteEntries(entries) {
    var many = entries.length > 1;
    confirmDialog({
      title: many ? "Delete " + entries.length + " items?" : "Delete “" + entries[0].name + "”?",
      message: "They go to the Recycle Bin on the phone, where they can be restored for 30 days.",
      confirmLabel: "Delete",
      danger: true,
    }).then(function (yes) {
      if (!yes) return;
      var paths = entries.map(function (entry) { return joinPath(state.path, entry.name); });
      request("POST", rootUrl("delete"), { json: { paths: paths } }).then(
        function (result) {
          reportBatch(result, "moved to the Recycle Bin");
          loadDirectory(true);
        },
        function (error) { toast(describeError(error), true); }
      );
    });
  }

  function reportBatch(result, doneWords) {
    var parts = [];
    if (result.completed) parts.push(result.completed + " " + doneWords);
    if (result.skipped) parts.push(result.skipped + " skipped");
    if (result.failed) parts.push(result.failed + " failed");
    var problem = (result.results || []).filter(function (item) { return item.status !== "completed" && item.message; })[0];
    var text = (parts.join(" · ") || "Nothing to do") + (problem ? ". " + problem.message : "");
    toast(text, result.failed > 0);
  }

  // --------------------------------------------------- move / copy + picker

  function moveOrCopy(entries, isMove) {
    pickFolder({
      title: (isMove ? "Move " : "Copy ") + (entries.length === 1 ? "“" + entries[0].name + "”" : entries.length + " items") + " to…",
      confirmLabel: isMove ? "Move here" : "Copy here",
    }).then(function (choice) {
      if (!choice) return;
      var sources = entries.map(function (entry) { return joinPath(state.path, entry.name); });
      request("POST", rootUrl(isMove ? "move" : "copy"), {
        json: { sources: sources, destination: choice.path, conflict: choice.conflict },
      }).then(
        function (result) {
          reportBatch(result, isMove ? "moved" : "copied");
          loadDirectory(true);
        },
        function (error) { toast(describeError(error), true); }
      );
    });
  }

  function pickFolder(options) {
    var location = state.path;
    var pathLabel = h("p", { class: "picker-path" });
    var list = h("ul", { class: "picker-list" });
    var note = h("p", { class: "notice hidden", role: "status" });
    var upButton = button("Up", "up", { small: true, kind: "quiet", keepText: true });
    var conflict = "skip";

    var radios = [
      ["skip", "Skip"],
      ["keepBoth", "Keep both"],
      ["replace", "Replace"],
    ].map(function (pair) {
      return h(
        "label",
        null,
        h("input", { type: "radio", name: "conflict", value: pair[0], checked: pair[0] === "skip", onchange: function () { conflict = pair[0]; } }),
        pair[1]
      );
    });

    function refresh() {
      pathLabel.textContent = location;
      upButton.disabled = location === "/";
      list.replaceChildren(h("li", null, h("span", { class: "empty", text: "Loading…" })));
      note.classList.add("hidden");
      request("GET", rootUrl("entries"), { query: { path: location, limit: 500 } }).then(
        function (data) {
          var folders = data.entries.filter(function (entry) { return entry.type === "directory"; });
          folders.sort(function (a, b) { return collator.compare(a.name, b.name); });
          if (folders.length === 0) list.replaceChildren(h("li", null, h("span", { class: "empty", text: "No folders here" })));
          else {
            list.replaceChildren.apply(
              list,
              folders.map(function (folder) {
                return h(
                  "li",
                  null,
                  h("button", { type: "button", class: "name-btn", onclick: function () { location = joinPath(location, folder.name); refresh(); } }, icon("folder"), h("span", { class: "label", text: folder.name }))
                );
              })
            );
          }
          if (data.nextCursor) {
            note.textContent = "Only the first 500 items are shown.";
            note.classList.remove("hidden");
          }
        },
        function (error) {
          list.replaceChildren(h("li", null, h("span", { class: "empty", text: describeError(error) })));
        }
      );
    }

    upButton.addEventListener("click", function () { location = parentPath(location); refresh(); });
    refresh();

    var content = h(
      "div",
      null,
      h("div", { class: "toolbar" }, upButton, pathLabel),
      list,
      note,
      h("p", { text: "If a file with the same name is already there:" }),
      h("div", { class: "radio-row" }, radios)
    );

    return showDialog(options.title, content, [
      { label: "Cancel", value: null },
      { label: options.confirmLabel, value: "ok", kind: "primary", submit: true },
    ]).then(function (result) {
      return result === "ok" ? { path: location, conflict: conflict } : null;
    });
  }

  // ---------------------------------------------------------------- uploads

  var uploads = { items: [], running: false, policy: null, nextId: 1 };

  function queueUploads(files) {
    if (!files.length || !canWrite()) return;
    files.forEach(function (file) {
      uploads.items.push({
        id: uploads.nextId++,
        file: file,
        rootId: state.rootId,
        dir: state.path,
        status: "waiting",
        loaded: 0,
        message: "",
        row: null,
        bar: null,
        label: null,
      });
    });
    renderUploads();
    pump();
  }

  function collectDropped(dataTransfer) {
    var files = [];
    var skippedFolder = false;
    var items = dataTransfer.items;
    if (items && items.length) {
      for (var i = 0; i < items.length; i++) {
        var item = items[i];
        if (item.kind !== "file") continue;
        var entry = typeof item.webkitGetAsEntry === "function" ? item.webkitGetAsEntry() : null;
        if (entry && entry.isDirectory) {
          skippedFolder = true;
          continue;
        }
        var file = item.getAsFile();
        if (file) files.push(file);
      }
    } else {
      files = Array.prototype.slice.call(dataTransfer.files);
    }
    if (skippedFolder) toast("Folders can't be uploaded yet. Upload the files inside instead.", true);
    queueUploads(files);
  }

  function renderUploads() {
    var box = shell.uploads;
    if (uploads.items.length === 0) {
      box.classList.add("hidden");
      box.replaceChildren();
      return;
    }
    box.classList.remove("hidden");
    var list = h("ul");
    uploads.items.forEach(function (item) {
      item.label = h("span", { class: "s" });
      item.bar = h("span");
      item.row = h(
        "li",
        null,
        h("div", { class: "row" }, h("span", { class: "n", text: item.file.name, title: item.file.name }), item.label),
        h("div", { class: "bar" }, item.bar)
      );
      list.appendChild(item.row);
      paintUpload(item);
    });
    var active = uploads.items.some(function (item) { return item.status === "waiting" || item.status === "uploading"; });
    box.replaceChildren(
      h(
        "header",
        null,
        h("span", { class: "spacer", text: active ? "Uploading…" : "Uploads" }),
        active ? null : button("Clear", "close", { small: true, kind: "quiet", onclick: function () { uploads.items = []; renderUploads(); } })
      ),
      list
    );
  }

  function paintUpload(item) {
    if (!item.label || !item.bar) return;
    var percent = item.file.size > 0 ? Math.min(100, Math.round((item.loaded / item.file.size) * 100)) : item.status === "done" ? 100 : 0;
    item.bar.style.width = (item.status === "done" ? 100 : percent) + "%";
    var text;
    var tone = "s";
    if (item.status === "waiting") text = "Waiting";
    else if (item.status === "uploading") text = percent + "%";
    else if (item.status === "done") { text = "Done"; tone = "s good"; }
    else if (item.status === "skipped") text = "Skipped";
    else { text = item.message || "Failed"; tone = "s bad"; }
    item.label.textContent = text;
    item.label.className = tone;
  }

  function sendFile(item, overwrite) {
    return new Promise(function (resolve) {
      var xhr = new XMLHttpRequest();
      var url = "/api/v1/roots/" + encode(item.rootId) + "/content?path=" + encode(joinPath(item.dir, item.file.name)) + (overwrite ? "&overwrite=1" : "");
      xhr.open("PUT", url);
      xhr.setRequestHeader("Authorization", "Bearer " + state.token);
      xhr.upload.onprogress = function (event) {
        if (event.lengthComputable) {
          item.loaded = event.loaded;
          paintUpload(item);
        }
      };
      xhr.onload = function () {
        var code = null;
        if (xhr.status >= 400) {
          try { code = JSON.parse(xhr.responseText).error; } catch (_) { code = "error"; }
        }
        resolve({ status: xhr.status, code: code });
      };
      xhr.onerror = function () { resolve({ status: 0, code: "network" }); };
      xhr.onabort = function () { resolve({ status: 0, code: "network" }); };
      xhr.send(item.file);
    });
  }

  function askReplace(name) {
    var applyAll = h("input", { type: "checkbox", id: "apply-all" });
    var content = h("div", null, h("p", { text: "“" + name + "” is already in this folder." }), h("label", null, applyAll, " Do this for the rest of this upload"));
    return showDialog("Replace the existing file?", content, [
      { label: "Skip", value: "skip" },
      { label: "Replace", value: "replace", kind: "primary", submit: true },
    ]).then(function (choice) {
      var picked = choice || "skip";
      if (applyAll.checked) uploads.policy = picked;
      return picked;
    });
  }

  function uploadOne(item) {
    item.status = "uploading";
    paintUpload(item);
    return sendFile(item, false).then(function (result) {
      if (result.status === 409 && result.code === "already_exists") {
        var decide = uploads.policy ? Promise.resolve(uploads.policy) : askReplace(item.file.name);
        return decide.then(function (choice) {
          if (choice !== "replace") {
            item.status = "skipped";
            paintUpload(item);
            return null;
          }
          item.loaded = 0;
          return sendFile(item, true);
        });
      }
      return result;
    }).then(function (result) {
      if (result === null) return;
      if (result.status >= 200 && result.status < 300) {
        item.status = "done";
      } else if (result.status === 401) {
        item.status = "failed";
        item.message = "Signed out";
        endSession("Your session ended. Sign in again to continue.");
      } else {
        item.status = "failed";
        item.message = describeError({ code: result.code });
      }
      paintUpload(item);
    });
  }

  function pump() {
    if (uploads.running) return;
    uploads.running = true;
    uploads.policy = null;
    var anyDone = false;

    function next() {
      var item = uploads.items.filter(function (candidate) { return candidate.status === "waiting"; })[0];
      if (!item || !state.token) {
        uploads.running = false;
        if (shell) renderUploads();
        if (anyDone && shell && state.token) loadDirectory(true);
        return null;
      }
      return uploadOne(item).then(function () {
        if (item.status === "done") anyDone = true;
        return next();
      });
    }
    next();
  }

  // ------------------------------------------------------------------- boot

  function boot() {
    if (!state.token) {
      renderLogin(null);
      return;
    }
    enterApp();
  }

  boot();
})();
''';
