#!/usr/bin/env python3
"""Embeds assets/portal/* into lib/server/portal/portal_bundle.dart.

The web portal is edited as real files (assets/portal/index.html, portal.css,
portal.js) so it can be linted and viewed in a browser (see
tool/portal_mock_server.js). The phone's server serves it from Dart constants,
which cannot fail to load at runtime the way a bundled asset could. A test
(test/server/portal_bundle_test.dart) fails if the two drift apart, so after
editing the portal run:

    python tool/embed_portal.py
"""
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SOURCES = [
    ("portalIndexHtml", "index.html"),
    ("portalCss", "portal.css"),
    ("portalJs", "portal.js"),
]
OUT = os.path.join(ROOT, "lib", "server", "portal", "portal_bundle.dart")


def main() -> int:
    parts = [
        "// GENERATED by tool/embed_portal.py from assets/portal/* - do not edit by hand.\n",
        "// Edit the files in assets/portal/ and run: python tool/embed_portal.py\n",
        "// ignore_for_file: lines_longer_than_80_chars\n\n",
    ]
    for name, filename in SOURCES:
        path = os.path.join(ROOT, "assets", "portal", filename)
        with open(path, "r", encoding="utf-8", newline="") as handle:
            text = handle.read().replace("\r\n", "\n")
        if "'''" in text:
            print(f"{filename} contains ''' which cannot be embedded in a raw string", file=sys.stderr)
            return 1
        parts.append(f"/// Source: assets/portal/{filename}\n")
        parts.append(f"const String {name} = r'''{text}''';\n\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("".join(parts).rstrip("\n") + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
