import "package:flutter/services.dart" show PlatformException;

import "../../core/errors/app_failure.dart";
import "../pigeon/storage_api.g.dart";
import "android_storage_host.dart";

/// Adapts the Pigeon-generated [AndroidStorageApi] (the real platform-channel
/// client; generated by `dart run pigeon`, not committed) to the hand-written
/// [AndroidStorageHost] contract that `SafStorageBackend` depends on.
///
/// Two jobs, both deliberately boring:
///  - convert Pigeon's all-nullable message classes into the non-null domain
///    types (failing loudly if the native side ever omits a required field);
///  - translate [PlatformException] codes raised by `SafStorageHostApi.kt`
///    (`permission_revoked`, `not_found`, `io_error`) into typed [AppFailure]s,
///    so nothing above this layer ever parses a platform error string.
///
/// STATUS: compiles and is unit-tested against a fake [AndroidStorageApi]. It
/// has never talked to the real Kotlin side on a device.
final class PigeonAndroidStorageHost implements AndroidStorageHost {
  PigeonAndroidStorageHost({AndroidStorageApi? api}) : _api = api ?? AndroidStorageApi();

  final AndroidStorageApi _api;

  @override
  Future<SafTreeInfo?> openDocumentTree() async {
    final SafTreeMessage? tree = await _guard(_api.openDocumentTree);
    return tree == null ? null : _toTreeInfo(tree);
  }

  @override
  Future<List<SafTreeInfo>> persistedTrees() async {
    final List<SafTreeMessage> trees = await _guard(_api.persistedTrees);
    return trees.map(_toTreeInfo).toList();
  }

  @override
  Future<void> releasePersistedUri(String treeUri) =>
      _guard(() => _api.releasePersistedUri(treeUri));

  @override
  Future<List<SafEntryInfo>> listChildren(String treeUri, String parentDocumentId) async {
    final List<SafEntryMessage> entries =
        await _guard(() => _api.listChildren(treeUri, parentDocumentId));
    return entries.map(_toEntryInfo).toList();
  }

  @override
  Future<SafEntryInfo?> stat(String treeUri, String documentId) async {
    final SafEntryMessage? entry = await _guard(() => _api.stat(treeUri, documentId));
    return entry == null ? null : _toEntryInfo(entry);
  }

  @override
  Future<String> createDirectory(String treeUri, String parentDocumentId, String name) =>
      _guard(() => _api.createDirectory(treeUri, parentDocumentId, name));

  @override
  Future<String> createFile(
    String treeUri,
    String parentDocumentId,
    String name,
    String mimeType,
  ) => _guard(() => _api.createFile(treeUri, parentDocumentId, name, mimeType));

  @override
  Future<void> deleteDocument(String treeUri, String documentId) =>
      _guard(() => _api.deleteDocument(treeUri, documentId));

  @override
  Future<String> renameDocument(String treeUri, String documentId, String newName) =>
      _guard(() => _api.renameDocument(treeUri, documentId, newName));

  @override
  Future<int> openFileDescriptor(String treeUri, String documentId, String mode) =>
      _guard(() => _api.openFileDescriptor(treeUri, documentId, mode));

  @override
  Future<List<PickedFile>> pickFilesToCache() async {
    final List<PickedFileMessage> picked = await _guard(_api.pickFilesToCache);
    return picked.map(_toPickedFile).toList();
  }

  // --- mapping ---

  PickedFile _toPickedFile(PickedFileMessage message) {
    final String? cachePath = message.cachePath;
    final String? name = message.name;
    if (cachePath == null || name == null) {
      throw const UnexpectedFailure(debugDetail: "native picked-file message missing cachePath/name");
    }
    return PickedFile(
      cachePath: cachePath,
      name: name,
      sizeBytes: message.sizeBytes,
      mimeType: message.mimeType,
    );
  }

  SafTreeInfo _toTreeInfo(SafTreeMessage message) {
    final String? treeUri = message.treeUri;
    final String? rootDocumentId = message.rootDocumentId;
    if (treeUri == null || rootDocumentId == null) {
      throw const UnexpectedFailure(debugDetail: "native tree message missing treeUri/rootDocumentId");
    }
    return SafTreeInfo(
      treeUri: treeUri,
      displayName: message.displayName ?? rootDocumentId,
      rootDocumentId: rootDocumentId,
    );
  }

  SafEntryInfo _toEntryInfo(SafEntryMessage message) {
    final String? documentId = message.documentId;
    final String? name = message.name;
    if (documentId == null || name == null) {
      throw const UnexpectedFailure(debugDetail: "native entry message missing documentId/name");
    }
    return SafEntryInfo(
      documentId: documentId,
      name: name,
      kind: message.type == SafEntryTypeMessage.directory
          ? SafEntryKind.directory
          : SafEntryKind.file,
      sizeBytes: message.sizeBytes,
      lastModifiedMillis: message.lastModifiedMillis,
      mimeType: message.mimeType,
    );
  }

  // --- error translation ---

  Future<T> _guard<T>(Future<T> Function() call) async {
    try {
      return await call();
    } on PlatformException catch (error) {
      throw switch (error.code) {
        "permission_revoked" => PermissionRevokedFailure(debugDetail: error.message),
        _ => UnexpectedFailure(debugDetail: "${error.code}: ${error.message}"),
      };
    }
  }
}
